#!/bin/bash
 
if command -v colordiff ; then
  alias diff='colordiff'
fi

alias inetdns='dig myip.opendns.com @Resolver1.opendns.com +short'
alias inetip='curl -4 -s "http://icanhazip.com"'
alias l='ls -l'
alias ll='ls -la'
alias lll='ls -lart'
alias ls='ls -G'

if command -v git
  then
  . ~/.bash/app/git
fi

if command -v docker
  then
  . ~/.bash/app/docker
fi
