#!/bin/bash
 
if command -v colordiff >/dev/null 2>&1
  then
  alias diff='colordiff'
fi

alias inetdns='dig myip.opendns.com @Resolver1.opendns.com +short'
alias inetip='curl -4 -s "http://icanhazip.com"'
alias ls='ls --color'
alias l='ls -l'
alias ll='ls -la'
alias lll='ls -lart'
alias k='kubectl'

if command -v git >/dev/null 2>&1 
  then
  . ~/.bash/app/git
fi

if command -v docker >/dev/null 2>&1 
  then
  . ~/.bash/app/docker
fi

